server:
  port: 5000

# common log level
logging:
  level:
    root: INFO
  file:
    name: "log1.log"


raft:
  servers:
    - "localhost:5001"
  serversSpringAddress:
    - "localhost:5000"
  self: "localhost:5001"
  electionTimeout: 15000
  heartBeatFrequent: 10000
  clientTimeout: 10000
  log: "logs/log1.json"
  newServer: false

library:
  address: "libraries/library1"

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
