server:
  port: 9200

# common log level
logging:
  level:
    root: INFO
  file:
    name: "log2.log"

raft:
  servers:
    - "localhost:9401"
    - "localhost:9201"
    - "localhost:9301"
  serversSpringAddress:
    - "localhost:9400"
    - "localhost:9200"
    - "localhost:9300"
  self: "localhost:9201"

library:
  address: "libraries/basicLibrary2"

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
